# Generated by Django 4.1 on 2022-08-19 18:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('codigo_de_barras', models.BigIntegerField(blank=True, error_messages={'unique': 'Este código de barras já está cadastrado'}, null=True, unique=True, verbose_name='Código de Barras')),
                ('preco_de_venda', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço de Venda')),
                ('preco_de_custo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço de Custo')),
                ('unidade_de_venda', models.CharField(choices=[('UND', 'Unidade'), ('CX', 'Caixa'), ('KG', 'Quilograma'), ('LT', 'Litro'), ('MT', 'Metro Linear'), ('MT2', 'Metro Quadrado'), ('MT3', 'Metro Cubico')], max_length=3, verbose_name='Unidade de Venda')),
                ('data_de_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('situacao', models.CharField(choices=[('Fechada', 'Fechada'), ('Cancelada', 'Cancelada')], default='Fechada', max_length=9)),
                ('itens', models.ManyToManyField(related_name='venda', to='api.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ItensVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='api.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venda_itens', to='api.venda')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Saida', 'Saída'), ('Reajuste', 'Reajuste')], max_length=8)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='api.produto', verbose_name='Histórico')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0, error_messages={'Erro': 'A quantidade deve ser positiva'}, validators=[django.core.validators.MinValueValidator(0)])),
                ('ultima_entrada', models.DateTimeField(blank=True, default=None, null=True)),
                ('ultima_saida', models.DateTimeField(blank=True, default=None, null=True)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='api.produto')),
            ],
        ),
    ]
