# Generated by Django 4.1 on 2022-08-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_de_barras',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
