# Generated by Django 4.1 on 2022-08-15 18:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_produto_preco_de_custo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_de_barras',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_de_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_de_custo',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço de Custo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_de_venda',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço de Venda'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_de_venda',
            field=models.CharField(choices=[('UND', 'Unidade'), ('CX', 'Caixa'), ('KG', 'Quilograma'), ('LT', 'Litro'), ('MT', 'Metro Linear'), ('M2', 'Metro Quadrado'), ('M3', 'Metro Cubico')], max_length=3, verbose_name='Unidade de Venda'),
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Saida', 'Saída'), ('Reajuste', 'Reajuste')], max_length=8)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.produto', verbose_name='Histórico')),
            ],
        ),
    ]
