# Generated by Django 4.1 on 2022-08-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_estoque_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='unidade_de_venda',
            field=models.CharField(choices=[('UND', 'Unidade'), ('CX', 'Caixa'), ('KG', 'Quilograma'), ('LT', 'Litro'), ('MT', 'Metro Linear'), ('MT2', 'Metro Quadrado'), ('MT3', 'Metro Cubico')], max_length=3, verbose_name='Unidade de Venda'),
        ),
    ]
