# Generated by Django 4.1 on 2022-08-17 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_produto_unidade_de_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produto', verbose_name='Histórico'),
        ),
    ]
