# Generated by Django 4.1 on 2022-08-17 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_historico_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, error_messages={'Erro': 'A quantidade deve ser positiva'}, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_de_barras',
            field=models.BigIntegerField(blank=True, error_messages={'unique': 'Este código de barras já está cadastrado'}, null=True, unique=True, verbose_name='Código de Barras'),
        ),
    ]
