# Generated by Django 4.1 on 2022-08-19 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_estoque_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='api.produto', verbose_name='Histórico'),
        ),
    ]
